### ISSUE TITLE
Please specify samtools mpilleup flags to use

### ISSUE THREAD

**Issue by emjbishop** [adeschen/mpileupTools#1]
Thank you for creating this! Which samtools mpileup flags are expected for this tool?

It doesn't work on my pileup created from this command:
`samtools mpileup -f test.fasta test.bam > pileup_test.tsv`

My error:
```
[02/09 12:09:57] emmabishop@emmas-air:~/workspace/mpileupTools$ python2 parseMPileup.py -i ../pileup_test.tsv -p out_test
Input file is " ../pileup_test.tsv "
Output prefix file is " out_test "
Traceback (most recent call last):
  File "parseMPileup.py", line 243, in <module>
    parsePileup(inputFile, outputPrefix, separatedFiles)
  File "parseMPileup.py", line 207, in parsePileup
    lettersCount = extractCigarSeq(data[4], data[5], data[6], info);
IndexError: list index out of range
```

A snippet of my pileup:
```
[02/09 12:10:14] emmabishop@emmas-air:~/workspace/mpileupTools$ head ../pileup_test.tsv 
1	1	T	0	*	*
1	2	T	0	*	*
1	3	G	2	,,	20
1	4	A	2	,,	0/
1	5	C	3	,,,	223
1	6	C	2	,,	12
1	7	G	3	,,,	2/0
1	8	A	3	,,^?.	223
1	9	T	4	,,,.	12.3
1	10	G	2	,.	32
```

**Comment by adeschen** [comment]
Hi Emma,

We are currently using this tool with samtools version 1.9 and the flags are:

samtools mpileup -aABRQ0 -q0 -s 

We haven't have any issues for a while but the tool is tuned for our specific needs.

If you can manage to pinpoint the section of the pileup that is causing the issue, I can have a look at it and try to identify the cause.

Best,
Astrid

**Comment by emjbishop** [comment]
Thanks, Astrid. I used those flags and then it worked great!
